name: chatonfire
description: A chat app that runs on Fire(base).

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  firebase_auth: ^0.6.2
  cupertino_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true