name: xkcd_app
description: An app to display XKCD comics.

dependencies:
  http: "^0.12.0+1"
  path_provider:
  url_launcher: ^5.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  uses-material-design: true
